# Адрес мастерноды с открытым доступом к API, по умолчанию - мастернода разработчиков Minter
address = "https://minter-node-1.testnet.minter.network"
# Публичные ключи мастернод и процентное соотношение, суммарно 100, без знака % и только целое число
nodes = [ ["Mp5c87d35a7adb055f54140ba03c0eed418ddc7c52ff7a63fc37a0e85611388610", "60"],
 ["Mp5c87d35a7adb055f54140ba03c0eed418ddc7c52ff7a63fc37a0e85611388610", "40"] ]

# Адреса аккаунтов в виде "Mx..." и приватные ключи аккаунтов
accounts = [ ["Mx...","...."], 
    ["Mx...", "...."] ]

# Монета сети (в тестовой MNT, в рабочей BIP)
coin_net = "MNT"
# Время ожидания между делегированием (в минутах)
timeout = 11
# Минимальная сумма делегирования
min_amount = 1000