# Адрес мастерноды с открытым доступом к API, по умолчанию - мастернода разработчиков Minter
address = "https://api.minter.stakeholder.space"
# Правила для аккаунтов по нодам, в которых - публичные ключи мастернод и процентное соотношение,
# суммарно 100, без знака % и только целое число
nodes = [ 
	["rule1", "Mp77774337c2212ce5a9b57b9392daf5e11639f7fd38e1a16a584291ed3a98b777", "60"],
	["rule1", "Mp77774337c2212ce5a9b57b9392daf5e11639f7fd38e1a16a584291ed3a98b777", "30", "VALIDATOR"],
	["rule1", "", "10", "ROYALTY"]
]

# Приватные ключи аккаунтов с правилами делегирования
accounts = [ 
	["...", "rule1"],
	["...", "rule1"],
	["...", "rule1"] 
]
# Минимальная сумма делегирования для правил
min_amount = [
	["100", "rule1"]
]
# Время ожидания между делегированием (в минутах)
timeout = 10
# Тип сети main или test
chain = "main"
# Максимальный коэф. оплаты комиссии
max_gas = 2