# Адрес мастерноды с открытым доступом к API, по умолчанию - мастернода разработчиков Minter
address = "https://minter-nodes-1.mainnet.minter.network"
# Публичные ключи мастернод и процентное соотношение, суммарно 100, без знака % и только целое число
nodes = [ ["Mp77774337c2212ce5a9b57b9392daf5e11639f7fd38e1a16a584291ed3a98b777", "60"],
 ["Mp77774337c2212ce5a9b57b9392daf5e11639f7fd38e1a16a584291ed3a98b777", "30", "VALIDATOR"],
 ["", "10", "ROYALTY"] ]

# Адреса аккаунтов в виде "Mx..." и приватные ключи аккаунтов
accounts = [ ["Mx...","..."],
    ["Mx...","..."],
	["Mx...","..."] ]
# Монета сети (в тестовой MNT, в рабочей BIP)
coin_net = "BIP"
# Время ожидания между делегированием (в минутах)
timeout = 10
# Минимальная сумма делегирования
min_amount = 100
# Тип сети main или test
chain = "main"
# Максимальный коэф. оплаты комиссии
max_gas = 2